version: 2

workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Install deps via yarn
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
